version: '3'
services:
  mongo:
    image: mongo
    networks:
      - graylog

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    environment:
      - "http.host=0.0.0.0"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - graylog

  graylog:
    image: graylog/graylog:4.0
    ports:
      - "9000:9000"
      - "12201:12201"
      - "1514:1514"
      - "1514:1514/udp"
    networks:
      - graylog
    restart: always
    links:
      - mongo
      - elasticsearch
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://${INSTANCE_IP}:9000/

networks:
    graylog: