  - job_name: "Segundo Exporter" # Nome do job que vai coletar as métricas do primeiro exporter.
    scrape_interval: 5s
    static_configs:
      - targets: ['apipython:9000'] # Endereço do alvo monitorado, ou seja, o nosso primeiro exporter.