{
 "title": "Visão Inicial",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Astronauta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Qtd Astronautas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "numero_de_astronautas{job=\"Quinto Exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resumo App Local",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volumetria Total",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum by (instance,status_code) (increase(http_requests_total{instance=\"apipython:9000\"}[$__interval]))",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Volumetria By Endpoint",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 9, "x": 7, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum by (instance,status_code) (increase(http_requests_total{instance=\"apipython:9000\"}[$__interval]))",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Volumetria By Endpoint",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum by (instance,status_code) (increase(http_requests_total{instance=\"apipython:9000\"}[$__interval]))",
       "legendFormat": "{{status_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resumo Docker Local",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quantidade de Containers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(rate(container_last_seen{name=~\".+\"}[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Informações por Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Utilização de Memória",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "(container_memory_usage_bytes{container_label_com_docker_compose_service=~\"alertmanager|cadvisor|grafana|nginx|prometheus\",image!=\"\"} - container_memory_cache{container_label_com_docker_compose_service=~\"alertmanager|cadvisor|grafana|nginx|prometheus\",image!=\"\"})",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "Limit memory",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_spec_memory_limit_bytes{name=~\".+\"}) by (name) ",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Utilização de CPU %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(rate(container_cpu_user_seconds_total{container_label_com_docker_compose_service=~\"alertmanager|cadvisor|grafana|nginx|prometheus\",image!=\"\"}[5m]) * 100)",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "Tráfego de Entrada por Container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Tráfego de Saída por Container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}